const exampleTopLikedRecipes = [
  {
    method: [
      'Wash hands with soap and water.',
      'In a large skillet or saucepan, heat oil on medium heat.',
      'Add onion and celery and sauté until soft.',
      'Add the rest of the vegetables, broth, salt and pepper.',
      'Cover and simmer slowly for 30 minutes or until carrots and potatoes are tender.',
      'Refrigerate leftovers within 2 hours.',
    ],
    ingredients: [
      'vegetable oil',
      'onion',
      'celery',
      'carrot',
      'tomato',
      'potato',
      'zucchini',
      'parsley',
      'broth',
    ],
    favorites_IDs: ['60ed9f0d1aa0010c6e63c1c2'],
    commentsId: [
      '60ef2c58b496ca86ff458b80',
      '60ef2cb9d71e47870db6839f',
      '60ef2cbed71e47870db683a0',
      '60ef2e60d71e47870db683a1',
    ],
    _id: '60eae152addee6f2c68dc24c',
    recipeName: 'Veggie Stew',
    type: 'Soups',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FVeggie%20Stew.jpg?alt=media&token=bbbbb874-6746-487b-a098-62c9ecca0b5d',
    modifiedDate: '7/15/2021',
    modifiedTime: '6:03:40 PM',
    userId: '60ead04baddee6f2c68dc24b',
    __v: 0,
  },
  {
    method: [
      'Wash hands with soap and water.',
      'In a small bowl, stir cream cheese until smooth. Stir in yogurt and seasonings. Refrigerate while preparing muffins and vegetables.',
      'Toast English muffin halves. Spread 1 Tablespoon sauce on each muffin half.',
      'Place about 3 Tablespoons vegetables on each muffin half. Shake or sprinkle about ½ teaspoon cheese over each muffin half, if desired.',
    ],
    ingredients: [
      'cheese',
      'yogurt',
      'powder',
      'basil',
      'oregano',
      'bell pepper',
      'muffin',
      'broccoli',
      'cumin',
      'cauliflower',
      'carrot',
    ],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ebe5e8addee6f2c68dc24d',
    recipeName: 'Fresh Veggie Pizza',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '7/15/2021',
    modifiedTime: '6:04:05 PM',
    userId: '60ead04baddee6f2c68dc24b',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: ['60ec66b4075ae10f21d97097', '60ec66b4075ae10f21d97096'],
    commentsId: [],
    _id: '60ecabc5ebdc0c2afa956424',
    recipeName: 'test',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '13/07/2021',
    modifiedTime: '6:53:25 am',
    userId: '60ec66b4075ae10f21d97097',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed7ee55fedcd3ff6895731',
    recipeName: 'test111',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '14/07/2021',
    modifiedTime: '9:54:13 pm',
    userId: '60ec669d075ae10f21d97096',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed7eee5fedcd3ff6895732',
    recipeName: 'test222',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '13/07/2021',
    modifiedTime: '9:54:22 pm',
    userId: '60ec669d075ae10f21d97096',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed7f055fedcd3ff6895733',
    recipeName: 'test333',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '13/07/2021',
    modifiedTime: '9:54:45 pm',
    userId: '60ead3110d9544b3af79961d',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed7f0b5fedcd3ff6895734',
    recipeName: 'test444',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '13/07/2021',
    modifiedTime: '9:54:51 pm',
    userId: '60ead3110d9544b3af79961d',
    __v: 0,
  },
  {
    method: [
      '1. Wash hands with soap and water.',
      '2. In a small dish, mix together soy sauce, garlic powder and pepper. Set aside.',
      '3. In a large skillet over medium-high heat, sauté pork in oil until just lightly browned. If using ground pork, break into crumbles as it cooks.',
      '4. Add carrot, onion and chosen vegetables. Sauté until tender, stirring frequently.',
      '5. Stir in rice and soy sauce mixture, breaking up any clumps of rice. Continue to heat and stir until heated through.',
      '6. Refrigerate leftovers within 2 hours.',
    ],
    ingredients: [
      'garlic',
      'pork',
      'vegetable oil',
      'carrot',
      'onion',
      'broccoli',
      '2 cups cooled cooked rice (brown or white)',
      ' celery',
      'bell pepper',
      'peas',
      'snow peas',
    ],
    favorites_IDs: ['60ead04baddee6f2c68dc24b'],
    commentsId: [],
    _id: '60ed8f0c9a131b007e0f49ce',
    recipeName: 'Fried Rice with Pork',
    type: 'Lunch',
    userId: '60ead04baddee6f2c68dc24b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFried%20Rice%20with%20Pork.jpg?alt=media&token=b359cf6b-58ba-4b0c-8827-9be9e40f7aa8',
    isPrivate: false,
    modifiedDate: '7/15/2021',
    modifiedTime: '6:04:26 PM',
    __v: 0,
  },
  {
    method: [
      'Sauté beef, ginger and garlic powder in a skillet over medium-high heat until meat is browned.',
      'In a bowl, mix sugar, soy sauce, cornstarch, sesame oil, pepper flakes and water.',
      'Add sauce to beef and cook for 5 minutes. Add broccoli and cook until tender.',
      'Serve over cooked bulgur.',
      'Refrigerate leftovers within 2 hours.',
    ],
    ingredients: [
      'beef',
      'ginger',
      'garlic powder',
      'brown sugar',
      'soy sauce',
      'cornstarch',
      'sesame oil',
      'red pepper ',
      'broccoli',
      'bulgur',
    ],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed8f659a131b007e0f49cf',
    recipeName: 'Beef and Broccoli',
    type: 'Main Courses',
    userId: '60ead04baddee6f2c68dc24b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FBeef%20and%20Broccoli.jpg?alt=media&token=c01d1a05-4eb2-4a5b-8687-d503a01b896c',
    isPrivate: false,
    modifiedDate: '7/15/2021',
    modifiedTime: '6:06:30 PM',
    __v: 0,
  },
  {
    method: [
      'In a large mixing bowl, stir together mayonnaise, yogurt, mustard, vinegar and sugar.',
      'Add cooked potatoes, celery, onion and olives and stir to coat evenly.',
      'Refrigerate until ready to serve.',
      'Refrigerate leftovers within 2 hours.',
    ],
    ingredients: [
      'potato',
      'celery',
      'onion',
      'olive',
      'mayonnaise',
      'yogurt',
      'mustard',
      'vinegar',
      'sugar',
    ],
    favorites_IDs: ['60ead04baddee6f2c68dc24b'],
    commentsId: [],
    _id: '60ed8fb29a131b007e0f49d0',
    recipeName: 'Potato Salad',
    type: 'Salads',
    userId: '60ead04baddee6f2c68dc24b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FPotato%20Salad.png?alt=media&token=4b652871-591e-478d-b116-cd321deedab5',
    isPrivate: false,
    modifiedDate: '7/14/2021',
    modifiedTime: '12:46:31 PM',
    __v: 0,
  },
  {
    method: [
      'Wash hands with soap and water.',
      'Lightly grease and preheat a medium skillet over medium heat (300 degrees F in an electric skillet). Lay a tortilla flat on the skillet.',
      'Sprinkle cheese evenly over one half of the tortilla. Add cranberry sauce, turkey and spinach. Fold empty half of tortilla over filling. ',
      'Cover and cook on each side for 2 to 3 minutes, or until outside is golden brown and inside is heated through.',
      'Refrigerate leftovers within 2 hours.',
    ],
    ingredients: ['tortilla', 'cheese', 'cranberry', 'turkey', 'spinach'],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed90579a131b007e0f49d1',
    recipeName: 'Turkey Cranberry Quesadilla',
    type: 'Quesadillas',
    userId: '60ead04baddee6f2c68dc24b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FTurkey%20Cranberry%20Quesadilla.jpg?alt=media&token=59fdb38f-37e8-409f-8f8e-7e54a54c5a77',
    isPrivate: false,
    modifiedDate: '7/15/2021',
    modifiedTime: '6:07:59 PM',
    __v: 0,
  },
];

export default exampleTopLikedRecipes
  .sort(function (a, b) {
    return a.favorites_IDs.length - b.favorites_IDs.length;
  })
  .reverse();
