[
  {
    recipeName: 'Turkey Cranberry Quesadilla',
    type: 'Quesadillas',
    ingredients: ['tortilla', 'cheese', 'cranberry', 'turkey', 'spinach'],
    method: [
      'Wash hands with soap and water.',
      'Lightly grease and preheat a medium skillet over medium heat (300 degrees F in an electric skillet). Lay a tortilla flat on the skillet.',
      'Sprinkle cheese evenly over one half of the tortilla. Add cranberry sauce, turkey and spinach. Fold empty half of tortilla over filling. ',
      'Cover and cook on each side for 2 to 3 minutes, or until outside is golden brown and inside is heated through.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Vegetables and Turkey Stir-Fry',
    type: '',
    ingredients: [
      'oil',
      'celery',
      'mushrooms',
      'water chestnuts',
      'bok choy',
      'cabbage',
      'zucchini',
      'carrot',
      'broccoli',
      'garlic',
      'garlic powder',
      'ginger',
      'salt',
      'turkey',
      'sugar',
      'brown rice',
    ],
    method: [
      'Heat oil in a medium skillet over medium heat (300 degrees in an electric skillet).',
      'Add vegetables, garlic, ginger root and salt. Stir fry for 2 to 4 minutes.',
      'Reduce heat to prevent scorching. Add cooked turkey and sugar. Cook until vegetables are tender and turkey is heated through, about 2 to 3 minutes.',
      'Serve warm over rice or noodles.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Spicy Rice Casserole',
    type: '',
    ingredients: [
      'beef',
      'onion',
      'jalapeño pepper',
      'rice',
      'tomato',
      'water',
      'chili powder',
      'oregano leaves',
      'salt',
      'cheese',
    ],
    method: [
      'Brown meat in a large skillet over medium-high heat (350 degrees in an electric skillet). Drain fat.',
      'Add onion and peppers and cook for 8 to 10 minutes until vegetables are soft.',
      'Add rice, tomato, 2 cups water, and spices. Mix well and bring to a boil.',
      'Reduce heat to medium low, cover and simmer for 20 minutes. Add more water if needed.',
      'Sprinkle with cheese and serve.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'My Personal Pizza',
    type: '',
    ingredients: [
      'muffin',
      'pizza sauce',
      'cheese',
      'chicken',
      'beef',
      'salami',
    ],
    method: [
      'Wash hands with soap and water.',
      'Preheat oven to 400 degrees F.',
      'Lightly toast English muffin half.',
      'Spread sauce on muffin. Add cheese and toppings of your choice.',
      'Bake 5 to 7 minutes, or until muffin is lightly browned and cheese is melted. Allow to cool slightly before eating.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Asparagus Mushroom Melt',
    type: '',
    ingredients: [
      'muffins',
      'onion',
      'mushrooms',
      'vegetable oil',
      'asparagus',
      'thyme',
      'vinegar',
      'salt',
      'pepper',
      'cheese',
    ],
    method: [
      'Wash hands with soap and water.',
      'Toast muffin halves and place on a baking sheet in a single layer.',
      'In a large skillet over medium-high heat, sauté onion and mushrooms in oil, stirring often, until just beginning to brown.',
      'Add asparagus, thyme and vinegar. Sauté, stirring often, until asparagus is barely tender. Season lightly with salt and pepper.',
      'Divide the vegetable mixture equally onto the muffin halves. Top each muffin with shredded cheese.',
      'Broil muffins until the cheese melts. Watch carefully to avoid burning.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Garlic Ginger Ramen with Beef',
    type: '',
    ingredients: [
      'beef',
      'water',
      'noodles',
      'vegetable',
      'onion',
      'ginger',
      'garlic',
    ],
    method: [
      'Wash hands with soap and water.',
      'In a large skillet over medium-high heat (350 degrees F in an electric skillet), brown ground beef. Drain fat from the skillet. Drain fat from the skillet (see Note).',
      'Add water and ONE seasoning packet to cooked beef and mix well.',
      'Add vegetables, green onion, ginger and garlic. Bring to a boil over high heat.',
      'Add ramen noodles, reduce heat to low, and simmer 3 to 5 minutes until vegetables are tender, stirring occasionally.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Ginger Almond Asparagus',
    type: '',
    ingredients: [
      'asparagus',
      'oil',
      'almonds',
      'salt',
      'pepper',
      'sugar',
      'ginger',
    ],
    method: [
      'Slice the asparagus diagonally into pieces about ¾ inch long.',
      'Heat oil in a large skillet over medium heat. Add remaining ingredients. Stir and sauté until asparagus is a brighter green, 3-5 minutes.',
      'Reduce heat to medium-low; cover and cook until the asparagus is just fork-tender. Avoid overcooking. Shake the pan occasionally to prevent sticking or burning.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Mix and Match Skillet Meal',
    type: '',
    ingredients: [
      'grain',
      'vegetables',
      'protein',
      'sauce',
      'spices',
      'topping',
    ],
    method: [
      'Combine all ingredients except topping in a large skillet.',
      'Bring to a boil. Then reduce heat to low. Cover and simmer until grains are tender, about 15 to 45 minutes. Stir occasionally and add liquid if too dry.',
      'Add topping before serving.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Skillet-Braised Chicken',
    type: '',
    ingredients: [
      'chicken',
      'vegetable oil',
      'salt',
      'pepper',
      'onion powder',
      'garlic powder',
    ],
    method: [
      'Wash hands with soap and water.',
      'Season the chicken. In a lightly oiled skillet over medium-high heat, sauté the chicken for one minute on each side until lightly browned.',
      'Cover the skillet with a tight-fitting lid. Reduce the heat to low. Cook for 10 minutes. Do not lift the lid.',
      'Turn off the heat. Let the chicken rest for 10 minutes. Do not remove the lid.',
      'The chicken is safely cooked when the internal temperature is at least 165 degrees F. Check in the thickest part with a food thermometer. If not done, cover and return to low heat for 3 to 5 minutes and check for doneness.',
      'Refrigerate leftovers within 2 hours or freeze for longer storage.',
    ],
  },
  {
    recipeName: 'One-Pan Chicken Alfredo',
    type: '',
    ingredients: [
      'vegetable oil',
      'flour',
      'chicken',
      'milk',
      'garlic',
      'onion',
      'basil',
      'pasta',
      'broccoli',
      'cheese',
    ],
    method: [
      'Wash hands with soap and water.',
      'In a skillet over medium-high heat, brown chicken in oil.',
      'Add flour, broth, milk, spices and pasta to skillet and stir well.',
      'Bring to a boil, then reduce heat to simmer and cover. Cook until pasta is almost tender, stirring occasionally.',
      'Add broccoli, cover, and cook until broccoli is tender.',
      'Remove from heat and stir in cheese.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Wontons',
    type: '',
    ingredients: [
      'onion',
      'salt',
      'sugar',
      'cumin',
      'ginger',
      'pepper',
      'cinnamon',
      'cornstarch',
      'sesame oil',
      'chicken',
      'cabbage',
      'carrot',
      'wrappers',
      'egg',
    ],
    method: [
      'Combine spices, cornstarch, and oil in a large bowl.',
      'Add cooked meat and vegetables. Mix well.',
      'Place 1 tablespoon of mixture in the center of each wonton wrapper.',
      'Brush wrapper edges with water or egg white.',
      'Fold wrapper diagonally so corners line up, and press edges together to seal.',
      'Bring the side two corners together over the pouch of filling and pinch to close.',
      'Spray a steamer basket with nonstick spray. Add wontons so they do not touch. Cover and steam over simmering water for 6-7 minutes.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Sesame Broccoli',
    type: '',
    ingredients: [
      'sesame seeds',
      'water',
      'vinegar',
      'soy sauce',
      'sugar',
      'red pepper flakes',
      'vegetable oil',
      'broccoli',
    ],
    method: [
      'Toast sesame seeds (if using) in a dry skillet on medium-high heat for 3 minutes or until golden brown. Set aside.',
      'In a medium skillet, sauté broccoli in oil over medium heat for 2 to 3 minutes.',
      'In a small bowl, combine water, vinegar, soy sauce, sugar, cornstarch, and red pepper flakes (if using).',
      'Add the sauce mixture to the broccoli in the skillet. Stir and cook until broccoli is tender and the sauce has thickened, about 3 to 5 minutes. Sprinkle with toasted sesame seeds (optional). Serve.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    name: '',
  },
];
