recipeExample = [
  {
    recipeName: 'Beef Soup',
    userId: '60e6c9f28b54e40587009a4b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FbeefSoup.png?alt=media&token=ac8e8759-6f24-4fda-badf-a7d3bb49c4b3',
    type: 'Soups',
    method:
      'In a large pot or dutch oven, cook beef in oil over medium heat until brown, Dissolve bouillon in water and pour into pot. Stir in rosemary, parsley and pepper, Bring it to a boil, then reduce heat, cover and simmer 1 hour,Stir potatoes, carrots, celery, and onion into the pot,Dissolve cornstarch in 2 teaspoons cold water and stir into stew,Cover and simmer 1 hour more.',
    ingredients: ['beef', 'vegetable oil', 'onion'],
    favorites_IDs: [],
    isPrivate: false,
    commentsId: [],
  },
  {
    recipeName: 'Veggie Stew',
    type: 'Soups',
    method: [
      'Wash hands with soap and water.',
      'In a large skillet or saucepan, heat oil on medium heat.',
      'Add onion and celery and sauté until soft.',
      'Add the rest of the vegetables, broth, salt and pepper.',
      'Cover and simmer slowly for 30 minutes or until carrots and potatoes are tender.',
      'Refrigerate leftovers within 2 hours.',
    ],

    ingredients: [
      '1 Tablespoon vegetable oil',
      '1/2 cup diced onion (1/2 medium onion)',
      '2 stalks celery, chopped',
      '2 carrots, sliced in 2” sticks',
      '1 can (15 ounces) diced tomatoes, with juice',
      '1 medium potato, diced',
      '1 zucchini (sliced 1/4 inch thick)',
      '2 Tablespoons minced parsley',
      '1 cup broth (any type)',
      '1/2 teaspoon salt',
      '1/2 teaspoon pepper',
    ],
  },

  {
    recipeName: 'Banana Berry Smoothie',
    type: 'Drinks',
    ingredients: [
      '1 cup sliced banana',
      '1 cup unsweetened frozen berries',
      '1 cup nonfat or 1% milk',
      '1 cup orange juice',
    ],
    method: [
      'Wash hands with soap and water.',
      'Place all ingredients in a blender. Put the lid on tightly.',
      'Blend until smooth. If too thick, add 1/2 cup cold water and blend again.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Fried Rice with Pork',
    type: 'Lunch',
    ingredients: [
      '2 Tablespoons low-sodium soy sauce',
      '½ teaspoon garlic powder or 2 cloves of garlic, minced',
      '1 teaspoon black pepper',
      '½ pound lean pork, ground or small cubes',
      '1 teaspoon vegetable oil',
      '¼ cup sliced or grated carrot',
      '1 cup chopped onion',
      '1 cup chopped vegetables, fresh, frozen or leftovers (try broccoli, celery, bell pepper, peas or snow peas)',
      '2 cups cooled cooked rice (brown or white)',
    ],
    method: [
      '1. Wash hands with soap and water.',
      '2. In a small dish, mix together soy sauce, garlic powder and pepper. Set aside.',
      '3. In a large skillet over medium-high heat, sauté pork in oil until just lightly browned. If using ground pork, break into crumbles as it cooks.',
      '4. Add carrot, onion and chosen vegetables. Sauté until tender, stirring frequently.',
      '5. Stir in rice and soy sauce mixture, breaking up any clumps of rice. Continue to heat and stir until heated through.',
      '6. Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Beef and Broccoli',
    type: 'Main Courses',
    ingredients: [
      '¾ pound lean ground beef',
      '¼ teaspoon ground ginger',
      '¾ teaspoon garlic powder',
      '2 Tablespoons packed brown sugar',
      '¼ cup low-sodium soy sauce',
      '2 teaspoons cornstarch',
      '1 Tablespoon sesame oil',
      '¼ teaspoon red pepper flakes',
      '½ cup water',
      '4 cups chopped broccoli (fresh or frozen)',
      '3 cups cooked bulgur',
    ],
    method: [
      '1. Sauté beef, ginger and garlic powder in a skillet over medium-high heat until meat is browned.',
      '2. In a bowl, mix sugar, soy sauce, cornstarch, sesame oil, pepper flakes and water.',
      '3. Add sauce to beef and cook for 5 minutes. Add broccoli and cook until tender.',
      '4. Serve over cooked bulgur.',
      '5. Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Potato Salad',
    type: 'Salads',
    ingredients: [
      '6 cups cooked potatoes, cubed into bite-sized pieces (about 6 small potatoes)',
      '1 ½ cups chopped celery (about 3 stalks)',
      '¼ cup chopped onion (1⁄4 medium onion)',
      '¼ cup sliced black olives',
      '½ cup light mayonnaise',
      '½ cup nonfat, plain yogurt',
      '1 Tablespoon prepared mustard',
      '1 Tablespoon vinegar',
      '1 Tablespoon sugar',
    ],
    method: [
      'In a large mixing bowl, stir together mayonnaise, yogurt, mustard, vinegar and sugar.',
      'Add cooked potatoes, celery, onion and olives and stir to coat evenly.',
      'Refrigerate until ready to serve.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Fresh Veggie Pizza',
    type: 'Pizza',
    ingredients: [
      '¼ cup (2 ounces) reduced-fat cream cheese, softened',
      '1/3 cup low-fat plain yogurt',
      '1/8 teaspoon garlic powder',
      '¼ teaspoon basil or cumin',
      '¼ teaspoon oregano',
      '1/8 teaspoon salt',
      '1/8 teaspoon pepper',
      '4 whole-wheat English muffins',
      '1 ½ cups finely chopped or grated vegetables (try a combination of broccoli, cauliflower, carrot, green pepper and bell pepper)',
      '2 Tablespoons grated parmesan cheese (optional)',
    ],
    method: [
      'Wash hands with soap and water.',
      'In a small bowl, stir cream cheese until smooth. Stir in yogurt and seasonings. Refrigerate while preparing muffins and vegetables.',
      'Toast English muffin halves. Spread 1 Tablespoon sauce on each muffin half.',
      'Place about 3 Tablespoons vegetables on each muffin half. Shake or sprinkle about ½ teaspoon cheese over each muffin half, if desired.',
    ],
  },
  {
    recipeName: 'Turkey Cranberry Quesadilla',
    type: 'Quesadillas',
    ingredients: [
      '1 8-inch whole-wheat tortilla',
      '2 Tablespoons shredded mozzarella cheese',
      '2 Tablespoons cranberry sauce or dried cranberries',
      '2 Tablespoons chopped or shredded cooked turkey',
      '⅓ cup spinach',
    ],
    method: [
      'Wash hands with soap and water.',
      'Lightly grease and preheat a medium skillet over medium heat (300 degrees F in an electric skillet). Lay a tortilla flat on the skillet.',
      'Sprinkle cheese evenly over one half of the tortilla. Add cranberry sauce, turkey and spinach. Fold empty half of tortilla over filling. ',
      'Cover and cook on each side for 2 to 3 minutes, or until outside is golden brown and inside is heated through.',
      'Refrigerate leftovers within 2 hours.',
      'Notes',
      'Substitute beans, tofu, or other cooked meat for the turkey.',
      'For extra flavor, add a dash of cayenne pepper or chili powder before folding the quesadilla in half.',
    ],
  },
  {
    recipeName: 'Cheesy Beef Pasta',
    type: '',
    ingredients: [
      '½ pound lean ground beef (15% fat)',
      '1 onion, diced (about 1 cup)',
      '2 cloves garlic, minced, or 1/2 teaspoon garlic powder',
      '1 small zucchini, chopped (about 1 1/2 cups)',
      '1 jar (24 to 26 ounces) tomato-based pasta sauce',
      '½ teaspoon dried basil',
      '½ teaspoon dried oregano',
      '¼ teaspoon red pepper flakes (optional)',
      '12 ounces rotini pasta (about 4 cups)',
      '1/2 cup (2 ounces) shredded cheddar cheese ',
      '1 1/2 cups (6 ounces) shredded mozzarella cheese ',
    ],
    method: [
      'In a large skillet, cook beef, onion, garlic and zucchini over medium-high heat (350 degrees F in an electric skillet) until meat is browned and broken into pieces. Drain any fat.',
      'Add the pasta sauce, basil, oregano and red pepper flakes, if desired. Bring to a simmer and cook on medium low (275 degrees F in an electric skillet) for 15 minutes.',
      'Cook the pasta in boiling water according to package directions.',
      'Drain the pasta and add to the sauce in the skillet. Stir in the cheese and cover until the cheese is melted.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
  {
    recipeName: 'Favorite Pancakes (with Eggs)',
    type: '',
    ingredients: [
      '1 ¼ cups all-purpose flour',
      '1 Tablespoon baking powder',
      '1 Tablespoon sugar',
      '¼ teaspoon salt',
      '¼ teaspoon spice such as cinnamon, nutmeg, or pumpkin spice (optional)',
      '1 egg',
      '1 cup non-fat or 1% milk (add 2 Tablespoons for thinner pancakes)',
      '2 Tablespoons vegetable oil',
      '1 teaspoon vanilla (optional)',
    ],
    method: [
      'Mix together flour, baking powder, sugar and salt in a medium bowl. Add the spice, if desired.',
      'In a separate bowl, beat egg until well blended. Add milk and oil. Add the vanilla, if desired.',
      'Add liquids to dry ingredients and stir just until lumps disappear.',
      'Lightly spray a large skillet or griddle with non-stick cooking spray or lightly wipe with oil. Heat skillet or griddle over medium-high heat (350 degrees in an electric skillet). The skillet is hot enough when a few drops of water sprinkled on it skitter and bounce around.',
      'Pour about ¼ cup of batter per pancake onto the hot skillet or griddle. Cook until bubbles come to the surface of the pancake and the edges start to look dry. Turn over. Cook until cooked through and the bottom is golden brown.',
      'Refrigerate leftover pancakes and enjoy them reheated for up to 2 days.',
    ],
  },
  {
    recipeName: 'Cranberry Applesauce',
    type: '',
    ingredients: [
      '3 ½ pounds apples, peeled, cored, and roughly chopped (8 to 9 medium apples)',
      '1 cup water',
      '1 ½ cups cranberries (fresh or frozen)',
      '½ teaspoon cinnamon',
      '½ teaspoon salt',
      '⅓ cup packed brown sugar',
      '2 Tablespoons lemon juice (optional)',
    ],
    method: [
      'Wash hands with soap and water.',
      'In a large saucepan, combine all ingredients. Bring to a boil, then lower heat to simmer. Cover and cook 20 to 30 minutes.',
      'Remove from heat and let cool slightly. Use a potato masher or fork to mash mixture to the consistency you want. Serve warm or cold.',
      'Refrigerate leftovers within 2 hours.',
    ],
  },
];

const another = [
  {
    method: [
      'Wash hands with soap and water.',
      'In a large skillet or saucepan, heat oil on medium heat.',
      'Add onion and celery and sauté until soft.',
      'Add the rest of the vegetables, broth, salt and pepper.',
      'Cover and simmer slowly for 30 minutes or until carrots and potatoes are tender.',
      'Refrigerate leftovers within 2 hours.',
    ],
    ingredients: [
      'vegetable oil',
      'onion',
      'celery',
      'carrot',
      'tomato',
      'potato',
      'zucchini',
      'parsley',
      'broth',
    ],
    favorites_IDs: ['60ed9f0d1aa0010c6e63c1c2'],
    commentsId: [
      '60ef2c58b496ca86ff458b80',
      '60ef2cb9d71e47870db6839f',
      '60ef2cbed71e47870db683a0',
      '60ef2e60d71e47870db683a1',
      '60f15238390196e7f0b89797',
    ],
    _id: '60eae152addee6f2c68dc24c',
    recipeName: 'Veggie Stew',
    type: 'Soups',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FVeggie%20Stew.jpg?alt=media&token=bbbbb874-6746-487b-a098-62c9ecca0b5d',
    modifiedDate: '7/15/2021',
    modifiedTime: '6:03:40 PM',
    userId: '60ead04baddee6f2c68dc24b',
    __v: 0,
  },
  {
    method: [
      'Wash hands with soap and water.',
      'In a small bowl, stir cream cheese until smooth. Stir in yogurt and seasonings. Refrigerate while preparing muffins and vegetables.',
      'Toast English muffin halves. Spread 1 Tablespoon sauce on each muffin half.',
      'Place about 3 Tablespoons vegetables on each muffin half. Shake or sprinkle about ½ teaspoon cheese over each muffin half, if desired.',
    ],
    ingredients: [
      'cheese',
      'yogurt',
      'powder',
      'basil',
      'oregano',
      'bell pepper',
      'muffin',
      'broccoli',
      'cumin',
      'cauliflower',
      'carrot',
    ],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ebe5e8addee6f2c68dc24d',
    recipeName: 'Fresh Veggie Pizza',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '7/15/2021',
    modifiedTime: '6:04:05 PM',
    userId: '60ead04baddee6f2c68dc24b',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: ['60ec66b4075ae10f21d97097', '60ec66b4075ae10f21d97096'],
    commentsId: [],
    _id: '60ecabc5ebdc0c2afa956424',
    recipeName: 'test',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '13/07/2021',
    modifiedTime: '6:53:25 am',
    userId: '60ec66b4075ae10f21d97097',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed7ee55fedcd3ff6895731',
    recipeName: 'test111',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '14/07/2021',
    modifiedTime: '9:54:13 pm',
    userId: '60ec669d075ae10f21d97096',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed7eee5fedcd3ff6895732',
    recipeName: 'test222',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '13/07/2021',
    modifiedTime: '9:54:22 pm',
    userId: '60ec669d075ae10f21d97096',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed7f055fedcd3ff6895733',
    recipeName: 'test333',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '13/07/2021',
    modifiedTime: '9:54:45 pm',
    userId: '60ead3110d9544b3af79961d',
    __v: 0,
  },
  {
    method: [],
    ingredients: [],
    favorites_IDs: [],
    commentsId: [],
    _id: '60ed7f0b5fedcd3ff6895734',
    recipeName: 'test444',
    type: 'Pizza',
    isPrivate: false,
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFresh%20Veggie%20Pizza.jpg?alt=media&token=c060fd8e-af24-45f5-8fe7-81b42e498186',
    modifiedDate: '13/07/2021',
    modifiedTime: '9:54:51 pm',
    userId: '60ead3110d9544b3af79961d',
    __v: 0,
  },
  {
    method: [
      '1. Wash hands with soap and water.',
      '2. In a small dish, mix together soy sauce, garlic powder and pepper. Set aside.',
      '3. In a large skillet over medium-high heat, sauté pork in oil until just lightly browned. If using ground pork, break into crumbles as it cooks.',
      '4. Add carrot, onion and chosen vegetables. Sauté until tender, stirring frequently.',
      '5. Stir in rice and soy sauce mixture, breaking up any clumps of rice. Continue to heat and stir until heated through.',
      '6. Refrigerate leftovers within 2 hours.',
    ],
    ingredients: [
      'garlic',
      'pork',
      'vegetable oil',
      'carrot',
      'onion',
      'broccoli',
      '2 cups cooled cooked rice (brown or white)',
      ' celery',
      'bell pepper',
      'peas',
      'snow peas',
    ],
    favorites_IDs: [
      '60ead04baddee6f2c68dc24b',
      '60e6c9f28b54e40587009a4b',
      '60ee4fdf6c812e0edfeab9fb',
    ],
    commentsId: ['60f18dc7390196e7f0b89799'],
    _id: '60ed8f0c9a131b007e0f49ce',
    recipeName: 'Fried Rice with Pork',
    type: 'Lunch',
    userId: '60ead04baddee6f2c68dc24b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FFried%20Rice%20with%20Pork.jpg?alt=media&token=b359cf6b-58ba-4b0c-8827-9be9e40f7aa8',
    isPrivate: false,
    modifiedDate: '7/15/2021',
    modifiedTime: '6:04:26 PM',
    __v: 0,
  },
  {
    method: [
      'Sauté beef, ginger and garlic powder in a skillet over medium-high heat until meat is browned.',
      'In a bowl, mix sugar, soy sauce, cornstarch, sesame oil, pepper flakes and water.',
      'Add sauce to beef and cook for 5 minutes. Add broccoli and cook until tender.',
      'Serve over cooked bulgur.',
      'Refrigerate leftovers within 2 hours.',
    ],
    ingredients: [
      'beef',
      'ginger',
      'garlic powder',
      'brown sugar',
      'soy sauce',
      'cornstarch',
      'sesame oil',
      'red pepper ',
      'broccoli',
      'bulgur',
    ],
    favorites_IDs: ['60ee4fdf6c812e0edfeab9fb'],
    commentsId: [
      '60f13c2a390196e7f0b89794',
      '60f13c38390196e7f0b89795',
      '60f13c49390196e7f0b89796',
    ],
    _id: '60ed8f659a131b007e0f49cf',
    recipeName: 'Beef and Broccoli',
    type: 'Main Courses',
    userId: '60ead04baddee6f2c68dc24b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FBeef%20and%20Broccoli.jpg?alt=media&token=c01d1a05-4eb2-4a5b-8687-d503a01b896c',
    isPrivate: false,
    modifiedDate: '7/15/2021',
    modifiedTime: '6:06:30 PM',
    __v: 0,
  },
  {
    method: [
      'In a large mixing bowl, stir together mayonnaise, yogurt, mustard, vinegar and sugar.',
      'Add cooked potatoes, celery, onion and olives and stir to coat evenly.',
      'Refrigerate until ready to serve.',
      'Refrigerate leftovers within 2 hours.',
    ],
    ingredients: [
      'potato',
      'celery',
      'onion',
      'olive',
      'mayonnaise',
      'yogurt',
      'mustard',
      'vinegar',
      'sugar',
    ],
    favorites_IDs: ['60ead04baddee6f2c68dc24b'],
    commentsId: [],
    _id: '60ed8fb29a131b007e0f49d0',
    recipeName: 'Potato Salad',
    type: 'Salads',
    userId: '60ead04baddee6f2c68dc24b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FPotato%20Salad.png?alt=media&token=4b652871-591e-478d-b116-cd321deedab5',
    isPrivate: false,
    modifiedDate: '7/14/2021',
    modifiedTime: '12:46:31 PM',
    __v: 0,
  },
  {
    method: [
      'Wash hands with soap and water.',
      'Lightly grease and preheat a medium skillet over medium heat (300 degrees F in an electric skillet). Lay a tortilla flat on the skillet.',
      'Sprinkle cheese evenly over one half of the tortilla. Add cranberry sauce, turkey and spinach. Fold empty half of tortilla over filling. ',
      'Cover and cook on each side for 2 to 3 minutes, or until outside is golden brown and inside is heated through.',
      'Refrigerate leftovers within 2 hours.',
    ],
    ingredients: ['tortilla', 'cheese', 'cranberry', 'turkey', 'spinach'],
    favorites_IDs: ['60ee4fdf6c812e0edfeab9fb'],
    commentsId: [],
    _id: '60ed90579a131b007e0f49d1',
    recipeName: 'Turkey Cranberry Quesadilla',
    type: 'Quesadillas',
    userId: '60ead04baddee6f2c68dc24b',
    picture:
      'https://firebasestorage.googleapis.com/v0/b/spiral-pics.appspot.com/o/images%2FTurkey%20Cranberry%20Quesadilla.jpg?alt=media&token=59fdb38f-37e8-409f-8f8e-7e54a54c5a77',
    isPrivate: false,
    modifiedDate: '7/15/2021',
    modifiedTime: '6:07:59 PM',
    __v: 0,
  },
];
